config/routes.rb
Rails.application.routes.draw do
  resources :photos, only: [:show, :update] do
    collection do
      match :search, via: [:get, :post]
      get :recent
    end
  end
  resources :actors, only: [:show], param: :name

  root "photos#index"

  get   "/auth/:provider/callback", to: "sessions#create"
  match "/logout",                  to: "sessions#destroy", as: :logout, via: [:get, :post]

  mount Sidekiq::Web => "/sidekiq"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/actor.rb
# ## Schema Information
#
# Table name: `actors`
#
# ### Columns
#
# Name              | Type               | Attributes
# ----------------- | ------------------ | ---------------------------
# **`id`**          | `integer`          | `not null, primary key`
# **`name`**        | `string(255)`      | `not null`
# **`created_at`**  | `datetime`         | `not null`
# **`updated_at`**  | `datetime`         | `not null`
#

class Actor < ApplicationRecord
  has_many :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
# ## Schema Information
#
# Table name: `photos`
#
# ### Columns
#
# Name                    | Type               | Attributes
# ----------------------- | ------------------ | ---------------------------
# **`id`**                | `integer`          | `not null, primary key`
# **`user_id`**           | `integer`          | `not null`
# **`original_post_id`**  | `integer`          | `not null`
# **`post_id`**           | `integer`          | `not null`
# **`actor_id`**          | `integer`          |
# **`width`**             | `integer`          |
# **`height`**            | `integer`          |
# **`url`**               | `string(255)`      | `not null`
# **`image`**             | `string(255)`      |
# **`average_hash`**      | `string(255)`      |
# **`has_downloaded`**    | `boolean`          | `default(FALSE), not null`
# **`created_at`**        | `datetime`         | `not null`
# **`updated_at`**        | `datetime`         | `not null`
#
# ### Indexes
#
# * `post_id`:
#     * **`post_id`**
# * `user_id_and_actor_id`:
#     * **`user_id`**
#     * **`actor_id`**
# * `user_id_and_url`:
#     * **`user_id`**
#     * **`url`**
#

class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :post
  belongs_to :actor, optional: true

  def suggest
    Photo.suggest(self.average_hash, self.id)
  end

  def save_with_actor(params)
    ActiveRecord::Base.transaction do
      if params[:actor]
        actor = Actor.find_or_create_by!(name: params[:actor][:name])
        self.actor = actor
      else
        self.actor_id = nil
      end
      self.save!
    end
  end

  def self.suggest(average_hash, exclude_photo_ids = [])
    suggests = Photo.pluck(:id, :average_hash).select { |(id, _)| Array(exclude_photo_ids).exclude?(id) }.map { |(id, hash)|
      if average_hash && hash
        sum = (hash.to_i(16) | average_hash.to_i(16)).to_s(2).count("1")
        mul = (hash.to_i(16) & average_hash.to_i(16)).to_s(2).count("1")
        [id, mul.to_f / sum]
      else
        [id, 0]
      end
    }.sort_by { |a| -a[1] }.take(16)
    photo_ids = suggests.map { |(id, _)| id }
    photo_idx = Photo.find(photo_ids).index_by(&:id)
    suggests.map { |(id, rate)| [photo_idx[id], rate] }
  end
end

app/models/post.rb
# ## Schema Information
#
# Table name: `posts`
#
# ### Columns
#
# Name               | Type               | Attributes
# ------------------ | ------------------ | ---------------------------
# **`id`**           | `integer`          | `not null, primary key`
# **`user_id`**      | `integer`          | `not null`
# **`original_id`**  | `integer`          | `not null`
# **`url`**          | `string(255)`      | `not null`
# **`posted_at`**    | `datetime`         | `not null`
# **`photo_count`**  | `integer`          | `default(1), not null`
# **`created_at`**   | `datetime`         | `not null`
# **`updated_at`**   | `datetime`         | `not null`
#
# ### Indexes
#
# * `user_id_and_original_id` (_unique_):
#     * **`user_id`**
#     * **`original_id`**
# * `user_id_and_posted_at`:
#     * **`user_id`**
#     * **`posted_at`**
# * `user_id_and_url`:
#     * **`user_id`**
#     * **`url`**
#

class Post < ApplicationRecord
  has_many :photos, dependent: :destroy
end

app/models/user.rb
# ## Schema Information
#
# Table name: `users`
#
# ### Columns
#
# Name                      | Type               | Attributes
# ------------------------- | ------------------ | ---------------------------
# **`id`**                  | `integer`          | `not null, primary key`
# **`name`**                | `string(255)`      | `not null`
# **`provider`**            | `string(255)`      | `not null`
# **`provider_user_id`**    | `string(255)`      | `not null`
# **`oauth_token`**         | `string(255)`      | `not null`
# **`oauth_token_secret`**  | `string(255)`      | `not null`
# **`created_at`**          | `datetime`         | `not null`
# **`updated_at`**          | `datetime`         | `not null`
#
# ### Indexes
#
# * `provider_and_provider_user_id` (_unique_):
#     * **`provider`**
#     * **`provider_user_id`**
#

class User < ApplicationRecord
  def self.create_or_update_with_omniauth(auth)
    user = User.find_or_initialize_by(provider: auth["provider"], provider_user_id: auth["uid"])

    user.name               = auth["info"]["nickname"]
    user.oauth_token        = auth["credentials"]["token"]
    user.oauth_token_secret = auth["credentials"]["secret"]
    user.save!

    user
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def show
    @actor = Actor.find_by(name: params[:name])
    @photos = @actor.photos
    render "photos/index"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  protect_from_forgery with: :exception

  def current_user
    unless defined?(@current_user)
      @current_user = User.find_by(id: session[:user_id])
    end
    @current_user
  end
  helper_method :current_user
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, only: [:show, :update]

  def index
    @photos = Photo.order("rand()").page(params[:page]).per(50)
  end

  def show
    @photo.actor ||= Actor.new
  end

  def search
    render and return unless params[:url]

    blob = open(params[:url]) { |f| f.read }
    image = Magick::Image.from_blob(blob)[0]
    @average_hash = AverageHash.calc_hash(image)
  end

  def recent
    @photos = Photo.order(id: :desc).take(50)
    render :index
  end

  def update
    @photo.save_with_actor(params[:photo])
    redirect_to photo_path(@photo)
  end

  private

    def find_photo
      @photo = Photo.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.create_or_update_with_omniauth(auth)

    reset_session
    session[:user_id] = user.id

    redirect_to root_path, notice: "Signed In!"
  end

  def destroy
    reset_session
    session[:user_id] = nil

    redirect_to root_path, notice: "Signed Out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for(:title) || "Tumblr Archiver"
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    meta[name="apple-mobile-web-app-capable" content="yes"]
    meta[name="mobile-web-app-capable" content="yes"]
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    - # Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!)
    - #= tag.link rel: "manifest", href: pwa_manifest_path(format: :json)
    link[rel="icon" href="/icon.png" type="image/png"]
    link[rel="icon" href="/icon.svg" type="image/svg+xml"]
    link[rel="apple-touch-icon" href="/icon.png"]
    - # Includes all stylesheet files in app/assets/stylesheets
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
  body
    = yield

app/views/photos/_suggest.html.slim
table
  - photos.each_slice(4) do |photo_array|
    tr
      - photo_array.each do |photo, rate|
        td
          = link_to(photo)
            = image_tag(photo.image.url, width: 50)
        td
          = rate.round(5)

app/views/photos/index.html.slim
table
  - @photos.each_slice(5) do |photo_array|
    tr
      - photo_array.each do |photo|
        td
          = link_to(photo)
            = image_tag(photo.image.url, width: 200)

app/views/photos/search.html.slim
= form_tag(search_photos_path)
  p
    = text_field_tag(:url)
    = submit_tag("検索")

- if @average_hash
  = image_tag(params[:url], height: 200)
  = render "suggest", photos: Photo.suggest(@average_hash)

app/views/photos/show.html.slim
= link_to("next", photo_path(@photo.id + 1))
table
  tr
    td
      = image_tag(@photo.image.url, width: 200)
    td
      table[border="1"]
        tr
          th photo_id
          td = @photo.id
        tr
          th actor
          td
            - if @photo.actor.new_record?
              = form_for(@photo) do |f|
                = f.fields_for(@photo.actor) do |actor_form|
                  = actor_form.text_field :name
                = f.submit
            - else
              = link_to(@photo.actor.name, actor_path(name: @photo.actor.name))
              = form_for(@photo) do |f|
                = f.hidden_field :actor_id, value: nil
                = f.submit "削除"
        tr
          th size
          td = "#{@photo.width}x#{@photo.height}"
        tr
          th posted_at
          td = @photo.post.posted_at
        tr
          th tumblr url
          td
            = link_to(@photo.post.url, @photo.post.url)

h2 histogram

table[cellpadding=0 cellspacing=0 style="border-collapse: collapse; border: 1px solid #000; background-color: #aaa;"]
  tr
    - color_table = [0, 51, 102, 153, 204, 255]
    - @photo.deserialized_color_hash.each_with_index do |v, i|
      - r = i / 36
      - g = (i - (r * 36)) / 6
      - b = i % 6
      td[style="vertical-align: bottom; height: 255px; margin: 0; padding: 0"]
        div[style="height: #{v / 128}px; background-color: rgb(#{color_table[r]},#{color_table[g]},#{color_table[b]});"]
          | &nbsp;

h2 suggest by color_hash
= render "suggest", photos: @photo.suggest_by_color

h2 suggest by average_hash
= render "suggest", photos: @photo.suggest